// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxWnSNwvRJbOwRL9o7VCRSj30en72ZFhk',
    appId: '1:395221273356:web:e1bfd0d096cae71ecb5729',
    messagingSenderId: '395221273356',
    projectId: 'papb-cfc91',
    authDomain: 'papb-cfc91.firebaseapp.com',
    storageBucket: 'papb-cfc91.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNz0iruThAy5ANDMQPuvSLVkUdMXru07k',
    appId: '1:395221273356:android:b7aede7504da6546cb5729',
    messagingSenderId: '395221273356',
    projectId: 'papb-cfc91',
    storageBucket: 'papb-cfc91.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwHjI0T9GM1bdOGqBfPHqnVLFIO_KmWbo',
    appId: '1:395221273356:ios:18f5199ceb5d814acb5729',
    messagingSenderId: '395221273356',
    projectId: 'papb-cfc91',
    storageBucket: 'papb-cfc91.appspot.com',
    iosBundleId: 'com.example.papb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwHjI0T9GM1bdOGqBfPHqnVLFIO_KmWbo',
    appId: '1:395221273356:ios:0446abd8c2c59d04cb5729',
    messagingSenderId: '395221273356',
    projectId: 'papb-cfc91',
    storageBucket: 'papb-cfc91.appspot.com',
    iosBundleId: 'com.example.papb.RunnerTests',
  );
}
